name: Ruff Linter Check & Env File Safeguard

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: ruff check

      - name: Check for .env files
        run: |
          if find . -type f -name ".env" | grep -q .; then
            echo ".env files found:"
            find . -type f -name ".env"
            exit 1
          else
            echo "No .env files found."
          fi
